---
language: ruby
cache: bundler
rvm: ruby-head
matrix:
  include:
    - rvm: ruby-head
      os: linux
      dist: xenial
    - rvm: ruby-head
      os: linux
      dist: groovy
      addons:
        apt:
          packages:
            - liburing-dev
    - rvm: ruby-head
      os: osx
    - rvm: ruby-head
  fast_finish: true

before_install: gem install bundler -v 2.1.4
script:
  - gem list -l
  - bundle exec rake compile
  - bundle exec rake

bundler_args: --jobs 1 --retry 3

notifications:
  email: false