---
language: ruby
cache: bundler
rvm: 2.7.1
matrix:
  include:
    - rvm: 2.7.1
      os: linux
      dist: xenial
    - rvm: 2.7.1
      os: linux
      dist: focal
      packages:
        - liburing-dev
    - rvm: 2.7.1
      os: osx
    - rvm: ruby-head
  allow_failures:
    - rvm: ruby-head
  fast_finish: true

before_install: gem install bundler -v 2.1.4
script:
  - gem list -l
  - bundle exec rake compile
  - bundle exec rake

bundler_args: --jobs 1 --retry 3

notifications:
  email: false