name: CI Tests
on:
  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: '0 7 * * SUN'
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
        - { os: ubuntu-20.04, ruby: '3.0', backend: epoll }
        - { os: ubuntu-20.04, ruby: '3.0', backend: ruby, disable-epoll: 1 }
        - { os: macos-11.0, ruby: '3.0', backend: kqueue }
        - { os: macos-11.0, ruby: '3.0', backend: ruby', disable-kqueue: 1 }
        - { os: windows-2019, ruby: mingw, backend: ruby }
        - { os: windows-2019, ruby: mswin, backend: ruby }
    name: test ${{ matrix.os }} ${{ matrix.ruby }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@master
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: false
      - name: Install Dependencies
        run: |
            gem install bundler
            bundle install --jobs 4 --retry 3
      - name: Compile
        env:
          DISABLE_EPOLL: ${{ matrix.disable-epoll }}
          DISABLE_KQUEUE: ${{ matrix.disable-kqueue }}
        run: rake compile
      - name: Test
        run: rake
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@master
        with:
          ruby-version: '3.0'
          bundler-cache: false
      - name: Install Dependencies
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
      - name: Build
        run: gem build evt.gemspec
